name = "MyFirstPackage"
uuid = "daecc9bd-0266-4a93-b081-4958a1c185c0"
authors = ["nzy1997"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.10"
LinearAlgebra = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
